import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const TRANSLATIONS = {
    fr: {
        "app.title": "OCEAN SECURITY",
        "nav.dashboard": "Tableau de bord",
        "nav.sites": "Mes Sites",
        "nav.equipment": "Inventaire",
        "nav.missions": "Missions",
        "nav.reports": "Rapports",
        "nav.certificates": "Certificats",
        "nav.support": "Support",
        "nav.logout": "Déconnexion",
        "nav.profile": "Mon Profil",
        "nav.settings": "Paramètres",
        "header.welcome": "Bienvenue",
        "stats.equipment": "Équipements",
        "stats.missions": "Missions cette année",
        "stats.compliance": "Taux de conformité",
        "stats.last_inspection": "Dernière inspection",
        "stats.total_equipment": "Total Équipements",
        "stats.active": "En Service",
        "stats.attention": "Attention Requise",
        "stats.inactive": "Hors Service",
        "stats.upcoming_missions": "Missions à venir",
        "stats.completed_missions": "Missions terminées",
        "common.status": "Statut",
        "common.actions": "Actions",
        "common.download": "Télécharger",
        "common.view": "Voir",
        "common.view_details": "Voir les détails",
        "common.search": "Rechercher...",
        "common.filter": "Filtrer",
        "common.export": "Exporter",
        "common.back": "Retour",
        "login.title": "Portail Client",
        "login.subtitle": "Accès sécurisé à vos rapports d'intervention, certificats de conformité et statistiques de sécurité.",
        "login.welcome": "Bon retour",
        "login.signin_text": "Veuillez vous connecter à votre compte",
        "login.email": "Adresse Email",
        "login.password": "Mot de passe",
        "login.forgot": "Mot de passe oublié ?",
        "login.signin": "Se Connecter",
        "login.security": "Accès Sécurisé",
        "login.encrypted": "Connexion chiffrée de bout en bout",
        "dashboard.title": "Tableau de bord",
        "dashboard.equipment_overview": "Vue d'ensemble des équipements",
        "dashboard.by_status": "Par Statut",
        "dashboard.recent_activity": "Activité Récente",
        "dashboard.pending_actions": "Actions En Attente",
        "dashboard.requires_maintenance": "Maintenance Requise",
        "dashboard.scheduled_year": "Prévues cette année",
        "dashboard.from_last_month": "depuis le mois dernier",
        "report.mission_report": "Rapport de Mission Technique",
        "report.ref": "Réf",
        "report.date": "Date",
        "report.site": "Site",
        "report.team_logistics": "Équipe et Logistique",
        "report.technicians": "Techniciens sur site",
        "report.transport": "Transport",
        "report.duration": "Durée d'intervention",
        "report.distance": "Distance parcourue",
        "report.technical_execution": "Exécution Technique",
        "report.equipment": "Équipement",
        "report.location": "Emplacement",
        "report.verification": "Vérifications",
        "report.specs": "Caractéristiques",
        "report.pressure": "Pression",
        "report.weight": "Poids",
        "report.mfg": "Fabrication",
        "report.analysis": "Analyse et Résultats",
        "report.recommendations": "Recommandations",
        "report.improvements": "Améliorations",
        "report.client_satisfaction": "Satisfaction Client",
        "report.rating": "Note",
        "report.comment": "Commentaire",
        "report.signature": "Signature",
        "report.approved_by": "Approuvé par",
        "status.compliant": "Conforme",
        "status.non_compliant": "Non Conforme",
        "status.attention": "Attention",
        "status.verified": "Vérifié",
        "status.recharged": "Rechargé",
        "status.replaced": "Remplacé",
        "equipment.subtitle": "Inventaire complet des dispositifs de sécurité incendie",
        "equipment.add": "Ajouter un équipement",
        "equipment.all_sites": "Tous les sites",
        "equipment.all_categories": "Toutes catégories",
        "equipment.search_placeholder": "Rechercher un équipement...",
        "missions.subtitle": "Programmez et suivez vos inspections de sécurité",
        "missions.request": "Demander une intervention",
        "missions.upcoming_recent": "À venir et récents",
        "missions.view_all": "Voir toutes les missions",
        "certificates.subtitle": "Consultez et gérez vos certificats de conformité",
        "certificates.issued": "Délivré le",
        "certificates.expires": "Expire le",
        "certificates.valid_until": "Valable jusqu'au",
        "certificates.cert_of_conformity": "CERTIFICAT DE CONFORMITÉ",
        "certificates.client_site": "Client / Site",
        "certificates.cert_details": "Détails de la certification",
        "certificates.mission_ref": "Réf Mission",
        "certificates.inspection_findings": "Résultats de l'inspection",
        "certificates.no_issues": "Aucune anomalie ou non-conformité constatée. Système entièrement conforme.",
        "certificates.no_data": "Aucune donnée détaillée trouvée.",
        "certificates.official_stamp": "CACHET OFFICIEL",
        "certificates.auth_signature": "Signature Autorisée",
        "certificates.generated_by": "Généré par le portail Ocean Security",
        "certificates.download_pdf": "Télécharger le certificat",
        "support.subtitle": "Nous sommes là pour assurer votre sécurité",
        "support.contact_us": "Contactez-nous",
        "support.name": "Nom",
        "support.email": "Email",
        "support.subject": "Sujet",
        "support.message": "Message",
        "support.send": "Envoyer le message",
        "support.hq_map": "Vue Carte Siège",
        "support.emergency_contact": "Contact d'Urgence",
        "support.emergency_text": "Disponible 24/7 pour les interventions urgentes de sécurité.",
        "support.office_info": "Infos Bureau",
        "table.id": "ID",
        "table.type": "Type",
        "table.category": "Catégorie",
        "table.site": "Site",
        "table.location": "Emplacement",
        "table.last_maint": "Dernière Maint.",
        "table.issue": "Problème",
        "table.action_taken": "Action prise",
        "sites.last_inspection": "Dernière Inspection",
        "sites.next_inspection": "Prochain Inspection",
        "sites.zone_distribution": "Zones",
        "sites.equipment_by_category": "Équipements par Catégorie",
        "common.unknown_site": "Site Inconnu",
        "certificates.status.active": "Actif",
        "certificates.status.expiring": "Expire Bientôt",
        "certificates.type": "Type",
        "certificates.pdf": "PDF",
        "support.report_issue": "Signaler un problème",
        "support.sales_inquiry": "Demande commerciale",
        "support.other": "Autre",
        "support.hq_address": "Route EL AIN Km 04, Sfax, Tunisie",
        "support.company_name": "OCEAN SECURITY HQ",
        "company.name": "OCEAN SECURITY",
        "company.tagline": "Services de Sécurité Incendie & Prévention",
    },
    en: {
        "app.title": "OCEAN SECURITY",
        "nav.dashboard": "Dashboard",
        "nav.sites": "My Sites",
        "nav.equipment": "Inventory",
        "nav.missions": "Missions",
        "nav.reports": "Reports",
        "nav.certificates": "Certificates",
        "nav.support": "Support",
        "nav.logout": "Logout",
        "nav.profile": "My Profile",
        "nav.settings": "Settings",
        "header.welcome": "Welcome",
        "stats.equipment": "Equipment",
        "stats.missions": "Missions this year",
        "stats.compliance": "Compliance Rate",
        "stats.last_inspection": "Last Inspection",
        "stats.total_equipment": "Total Equipment",
        "stats.active": "Active",
        "stats.attention": "Attention Required",
        "stats.inactive": "Out of Service",
        "stats.upcoming_missions": "Upcoming Missions",
        "stats.completed_missions": "Completed Missions",
        "common.status": "Status",
        "common.actions": "Actions",
        "common.download": "Download",
        "common.view": "View",
        "common.view_details": "View Details",
        "common.search": "Search...",
        "common.filter": "Filter",
        "common.export": "Export",
        "common.back": "Back",
        "login.title": "Client Portal",
        "login.subtitle": "Secure access to your intervention reports, compliance certificates, and safety statistics.",
        "login.welcome": "Welcome Back",
        "login.signin_text": "Please sign in to your account",
        "login.email": "Email Address",
        "login.password": "Password",
        "login.forgot": "Forgot password?",
        "login.signin": "Sign In",
        "login.security": "Secure Access",
        "login.encrypted": "End-to-end encrypted connection",
        "dashboard.title": "Dashboard",
        "dashboard.equipment_overview": "Global Equipment Overview",
        "dashboard.by_status": "By Status",
        "dashboard.recent_activity": "Recent Activity",
        "dashboard.pending_actions": "Pending Actions",
        "dashboard.requires_maintenance": "Requires maintenance",
        "dashboard.scheduled_year": "Scheduled for this year",
        "dashboard.from_last_month": "from last month",
        "report.mission_report": "Technical Mission Report",
        "report.ref": "Ref",
        "report.date": "Date",
        "report.site": "Site",
        "report.team_logistics": "Team & Logistics",
        "report.technicians": "Team on Site",
        "report.transport": "Transport",
        "report.duration": "Duration",
        "report.distance": "Distance",
        "report.technical_execution": "Technical Execution",
        "report.equipment": "Equipment",
        "report.location": "Location",
        "report.verification": "Verification",
        "report.specs": "Specifications",
        "report.pressure": "Pressure",
        "report.weight": "Weight",
        "report.mfg": "Mfg Date",
        "report.analysis": "Analysis & Results",
        "report.recommendations": "Recommendations",
        "report.improvements": "Improvements",
        "report.client_satisfaction": "Client Satisfaction",
        "report.rating": "Rating",
        "report.comment": "Comment",
        "report.signature": "Signature",
        "report.approved_by": "Approved by",
        "status.compliant": "Compliant",
        "status.non_compliant": "Non Compliant",
        "status.attention": "Attention",
        "status.verified": "Verified",
        "status.recharged": "Recharged",
        "status.replaced": "Replaced",
        "equipment.subtitle": "Full inventory of fire safety devices",
        "equipment.add": "Add Equipment",
        "equipment.all_sites": "All Sites",
        "equipment.all_categories": "All Categories",
        "equipment.search_placeholder": "Search equipment...",
        "missions.subtitle": "Schedule and track your safety inspections",
        "missions.request": "Request Intervention",
        "missions.upcoming_recent": "Upcoming & Recent",
        "missions.view_all": "View All Missions",
        "certificates.subtitle": "View and manage your compliance certificates",
        "certificates.issued": "Issued",
        "certificates.expires": "Expires",
        "certificates.valid_until": "Valid until",
        "certificates.cert_of_conformity": "CERTIFICATE OF CONFORMITY",
        "certificates.client_site": "Client / Site",
        "certificates.cert_details": "Certification Details",
        "certificates.mission_ref": "Mission Ref",
        "certificates.inspection_findings": "Inspection Findings",
        "certificates.no_issues": "No issues or non-conformities were found. System is fully compliant.",
        "certificates.no_data": "No detailed report data found.",
        "certificates.official_stamp": "OFFICIAL STAMP",
        "certificates.auth_signature": "Authorized Signature",
        "certificates.generated_by": "Generated by Ocean Security Portal",
        "certificates.download_pdf": "Download Certificate PDF",
        "support.subtitle": "We are here to help ensuring your safety",
        "support.contact_us": "Contact Us",
        "support.name": "Name",
        "support.email": "Email",
        "support.subject": "Subject",
        "support.message": "Message",
        "support.send": "Send Message",
        "support.hq_map": "Headquarters Map View",
        "support.emergency_contact": "Emergency Contact",
        "support.emergency_text": "Available 24/7 for urgent safety interventions.",
        "support.office_info": "Office Info",
        "table.id": "ID",
        "table.type": "Type",
        "table.category": "Category",
        "table.site": "Site",
        "table.location": "Location",
        "table.last_maint": "Last Maint.",
        "table.issue": "Issue",
        "table.action_taken": "Action Taken",
        "sites.last_inspection": "Last Inspection",
        "sites.next_inspection": "Next Inspection",
        "sites.zone_distribution": "Zone Distribution",
        "sites.equipment_by_category": "Equipment by Category",
        "common.unknown_site": "Unknown Site",
        "certificates.status.active": "Active",
        "certificates.status.expiring": "Expiring",
        "certificates.type": "Type",
        "certificates.pdf": "PDF",
        "support.report_issue": "Report an Issue",
        "support.sales_inquiry": "Sales Inquiry",
        "support.other": "Other",
        "support.hq_address": "Route EL AIN Km 04, Sfax, Tunisia",
        "support.company_name": "OCEAN SECURITY HQ",
        "company.name": "OCEAN SECURITY",
        "company.tagline": "Fire Safety & Prevention Services",
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('fr');

    const t = (key: string) => {
        // @ts-ignore
        return TRANSLATIONS[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
